version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foody
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d foody"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/foody
      RUN_MIGRATIONS: "1"
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      RECOVERY_SECRET: foodyDevRecover123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      # Web app should read API base from env or config (adjust if needed)
      FOODY_API: http://localhost:8080
      PORT: 3000
    depends_on:
      - backend
    ports:
      - "3000:3000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      # Set your secrets locally via .env or export before running compose
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_PUBLIC: http://localhost:3000
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      FOODY_API: http://backend:8080
      PORT: 8000
    depends_on:
      - backend
    ports:
      - "8000:8000"
